export const TERRITORIES = [
  "Barbados",
  "Trinidad & Tobago",
  "Jamaica",
  "Bahamas",
  "St. Lucia",
  "Grenada",
  "St. Vincent & the Grenadines",
  "Antigua & Barbuda",
  "Dominica",
  "St. Kitts & Nevis",
  "Aruba",
  "Curaçao",
  "Bonaire",
  "Sint Maarten",
  "Cayman Islands",
  "Turks & Caicos",
  "British Virgin Islands",
  "Anguilla",
  "Montserrat",
  "Guyana",
  "Suriname",
  "Belize",
  "Haiti",
  "Dominican Republic",
  "Other",
] as const;

export const COMPANY = {
  name: "Vibrand Caribbean Inc.",
  email: "sales@vibrand.com",
  phone: "+1 (246) 625-1000",
  location: "Saint Michael, Barbados",
  hours: "Mon–Fri, 8AM–5PM AST",
};
