/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminBulkImagesRouteImport } from './routes/_authenticated/admin.bulk-images'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminQuotesRouteImport } from './routes/_authenticated/admin.quotes'
import { Route as ApiPublicProductImageSplatRouteImport } from './routes/api/public/product-image.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminBulkImagesRoute =
  AuthenticatedAdminBulkImagesRouteImport.update({
    id: '/admin/bulk-images',
    path: '/admin/bulk-images',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/admin/categories',
    path: '/admin/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/admin/import',
    path: '/admin/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/admin/products',
    path: '/admin/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminQuotesRoute =
  AuthenticatedAdminQuotesRouteImport.update({
    id: '/admin/quotes',
    path: '/admin/quotes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicProductImageSplatRoute =
  ApiPublicProductImageSplatRouteImport.update({
    id: '/api/public/product-image/$',
    path: '/api/public/product-image/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/quote': typeof QuoteRoute
  '/c/$slug': typeof CSlugRoute
  '/admin/bulk-images': typeof AuthenticatedAdminBulkImagesRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/quotes': typeof AuthenticatedAdminQuotesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/product-image/$': typeof ApiPublicProductImageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/quote': typeof QuoteRoute
  '/c/$slug': typeof CSlugRoute
  '/admin/bulk-images': typeof AuthenticatedAdminBulkImagesRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/quotes': typeof AuthenticatedAdminQuotesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/product-image/$': typeof ApiPublicProductImageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/quote': typeof QuoteRoute
  '/c/$slug': typeof CSlugRoute
  '/_authenticated/admin/bulk-images': typeof AuthenticatedAdminBulkImagesRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/quotes': typeof AuthenticatedAdminQuotesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/product-image/$': typeof ApiPublicProductImageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/products'
    | '/quote'
    | '/c/$slug'
    | '/admin/bulk-images'
    | '/admin/categories'
    | '/admin/import'
    | '/admin/products'
    | '/admin/quotes'
    | '/admin/'
    | '/api/public/product-image/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/products'
    | '/quote'
    | '/c/$slug'
    | '/admin/bulk-images'
    | '/admin/categories'
    | '/admin/import'
    | '/admin/products'
    | '/admin/quotes'
    | '/admin'
    | '/api/public/product-image/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/products'
    | '/quote'
    | '/c/$slug'
    | '/_authenticated/admin/bulk-images'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/quotes'
    | '/_authenticated/admin/'
    | '/api/public/product-image/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ProductsRoute: typeof ProductsRoute
  QuoteRoute: typeof QuoteRoute
  CSlugRoute: typeof CSlugRoute
  ApiPublicProductImageSplatRoute: typeof ApiPublicProductImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/bulk-images': {
      id: '/_authenticated/admin/bulk-images'
      path: '/admin/bulk-images'
      fullPath: '/admin/bulk-images'
      preLoaderRoute: typeof AuthenticatedAdminBulkImagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/quotes': {
      id: '/_authenticated/admin/quotes'
      path: '/admin/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AuthenticatedAdminQuotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/product-image/$': {
      id: '/api/public/product-image/$'
      path: '/api/public/product-image/$'
      fullPath: '/api/public/product-image/$'
      preLoaderRoute: typeof ApiPublicProductImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminBulkImagesRoute: typeof AuthenticatedAdminBulkImagesRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminQuotesRoute: typeof AuthenticatedAdminQuotesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminBulkImagesRoute: AuthenticatedAdminBulkImagesRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminQuotesRoute: AuthenticatedAdminQuotesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ProductsRoute: ProductsRoute,
  QuoteRoute: QuoteRoute,
  CSlugRoute: CSlugRoute,
  ApiPublicProductImageSplatRoute: ApiPublicProductImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
